#!/usr/bin/env node
// Regenerates js/qr-codes.js from the URLs below.
//
// The QR codes are baked in at authoring time rather than rendered in the
// browser: the standalone build has to open from file:// with no network
// and no CDN, so a runtime QR library would be one more thing to bundle
// and one more way for the deck to break in a room with no wifi.
//
// Run `node tools/make-qr.mjs` after changing a URL.
import { writeFileSync } from "node:fs";
import QRCode from "qrcode";

const TARGETS = {
  careers: "https://softlandia.com/careers",
};

const entries = await Promise.all(
  Object.entries(TARGETS).map(async ([key, url]) => {
    const svg = await QRCode.toString(url, {
      type: "svg",
      errorCorrectionLevel: "M",
      margin: 1,
      color: { dark: "#0b0e17", light: "#ffffff" },
    });
    return [key, url, svg.replace(/\s+/g, " ").trim()];
  })
);

const body = entries
  .map(([key, url, svg]) => `  // ${url}\n  ${key}: \`${svg}\`,`)
  .join("\n");

writeFileSync(
  new URL("../js/qr-codes.js", import.meta.url),
  `// GENERATED by tools/make-qr.mjs — do not edit by hand.\n` +
    `// Re-run that script after changing a URL there.\n` +
    `export const qrCodes = {\n${body}\n};\n`
);

console.log(`Wrote js/qr-codes.js (${entries.map(([k]) => k).join(", ")})`);
